# Directory Settings
source: src
destination: deploy
plugins: plugins

# Site settings
title: StarGazer
subtitle: blub.
author: bloop.
email: pat@pdaily.me
description:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "stargazer.pdaily.me" # the base hostname & protocol for your site
twitter_user:

# Github stuffs
github_user: github
github_repo_count: 2
github_show_profile_link: true
github_skip_forks: true
# Dev settings, comment this out before pushing!
# host: 0.0.0.0

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
highlighter: pygments

# ----------------------- #
#   Jekyll-Assets Config  #
# ----------------------- #
assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/fonts
    - _assets/images
    - _assets/js
    - _assets/scss
  js_compressor:  uglifier
  css_compressor: sass
  cachebust: hard
  cache: ../.jekyll-assets-cache
  gzip: [ text/css, application/javascript ]
  version: 2
