# Directory Settings
source: src
destination: deploy
plugins: plugins

# Site settings
title: StarGazer
subtitle: blub.
author: bloop.
email: pat@pdaily.me
description:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "stargazer.pdaily.me" # the base hostname & protocol for your site
twitter_user:

# Github stuffs
github_user: 
github_repo_count: 2
github_show_profile_link: true
github_skip_forks: true

# Google +1
google_plus_one: false
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user:
googleplus_hidden: false

# Disqus Comments
disqus_short_name: pdaily
disqus_show_comment_count: false

# Google Analytics
google_analytics_tracking_id:

# Dev settings, comment this out before pushing!
# host: 0.0.0.0

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
highlighter: pygments

default_asides: [asides/recent_posts.html, asides/github.html, asides/googleplus.html]

# ----------------------- #
#   Jekyll-Assets Config  #
# ----------------------- #
assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/fonts
    - _assets/images
    - _assets/js
    - _assets/scss
  js_compressor:  uglifier
  css_compressor: sass
  cachebust: hard
  cache: ../.jekyll-assets-cache
  gzip: [ text/css, application/javascript ]
  version: 2
